"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROTOCOL_MARKETPLACE_ADDRESS = exports.PROTOCOL_MARKETPLACE_SLUG = exports.PROTOCOL_MARKETPLACE_NAME = exports.PROTOCOL_METHODOLOGY_VERSION = exports.PROTOCOL_SUBGRAPH_VERSION = void 0;
exports.PROTOCOL_SUBGRAPH_VERSION = "1.0.2";
exports.PROTOCOL_METHODOLOGY_VERSION = "1.0.0";
exports.PROTOCOL_MARKETPLACE_NAME = "Seaport";
exports.PROTOCOL_MARKETPLACE_SLUG = "seaport";
exports.PROTOCOL_MARKETPLACE_ADDRESS = "0x00000000006c3852cbef3e08e8df289169ede581";
