"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Deploy = void 0;
var Deploy;
(function (Deploy) {
    Deploy.UNISWAP_V3_ARBITRUM = 0;
    Deploy.UNISWAP_V3_BASE = 1;
    Deploy.UNISWAP_V3_BSC = 2;
    Deploy.UNISWAP_V3_CELO = 3;
    Deploy.UNISWAP_V3_ETHEREUM = 4;
    Deploy.UNISWAP_V3_OPTIMISM = 5;
    Deploy.UNISWAP_V3_POLYGON = 6;
    Deploy.PANCAKE_V3_BSC = 7;
    Deploy.PANCAKE_V3_ETHEREUM = 8;
    Deploy.SUSHISWAP_V3_ETHEREUM = 9;
    Deploy.SUSHISWAP_V3_ARBITRUM = 10;
    Deploy.SUSHISWAP_V3_AVALANCHE = 11;
    Deploy.SUSHISWAP_V3_BSC = 12;
    Deploy.SUSHISWAP_V3_FANTOM = 13;
    Deploy.SUSHISWAP_V3_FUSE = 14;
    Deploy.SUSHISWAP_V3_GNOSIS = 15;
    Deploy.SUSHISWAP_V3_MOONRIVER = 16;
    Deploy.SUSHISWAP_V3_OPTIMISM = 17;
    Deploy.SUSHISWAP_V3_POLYGON = 18;
})(Deploy = exports.Deploy || (exports.Deploy = {}));
