"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MINIPOOLSTATUS_DISSOLVED = exports.MINIPOOLSTATUS_WITHDRAWABLE = exports.MINIPOOLSTATUS_STAKING = exports.MINIPOOLSTATUS_PRELAUNCH = exports.MINIPOOLSTATUS_INITIALIZED = exports.RPLREWARDCLAIMERTYPE_NODE = exports.RPLREWARDCLAIMERTYPE_ODAO = exports.RPLREWARDCLAIMERTYPE_PDAO = exports.NODERPLSTAKETRANSACTIONTYPE_SLASHED = exports.NODERPLSTAKETRANSACTIONTYPE_WITHDRAWAL = exports.NODERPLSTAKETRANSACTIONTYPE_STAKED = void 0;
// Related to Node RPL Stake Transactions.
exports.NODERPLSTAKETRANSACTIONTYPE_STAKED = "Staked";
exports.NODERPLSTAKETRANSACTIONTYPE_WITHDRAWAL = "Withdrawal";
exports.NODERPLSTAKETRANSACTIONTYPE_SLASHED = "Slashed";
// Related to RPL Rewards Claims.
exports.RPLREWARDCLAIMERTYPE_PDAO = "PDAO";
exports.RPLREWARDCLAIMERTYPE_ODAO = "ODAO";
exports.RPLREWARDCLAIMERTYPE_NODE = "Node";
// Related to Minipool Status.
exports.MINIPOOLSTATUS_INITIALIZED = 0;
exports.MINIPOOLSTATUS_PRELAUNCH = 1;
exports.MINIPOOLSTATUS_STAKING = 2;
exports.MINIPOOLSTATUS_WITHDRAWABLE = 3;
exports.MINIPOOLSTATUS_DISSOLVED = 4;
